version: '3.8'

services:
  playerapi:
    build: .
    image: playerapi-deno
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PlayerDb
    ports:
      - "5432:5432"
    volumes:
      - playerdb_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: bash -c "apt-get update && apt-get install -y postgresql-client && docker-entrypoint.sh postgres"

networks:
  app-network:
    driver: bridge

volumes:
  playerdb_data:
