version: '3.8'

networks:
  player_network:
    driver: bridge

services:
  playerapi:
    build: .
    image: playerapi-node
    ports:
      - "80:8080"
    depends_on:
      - db_mysql
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db_postgres
      - PGDATABASE=playerdb
      - PGPORT=5432
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db_mysql
      - MYSQL_DATABASE=playerdb
      - MYSQL_PORT=3306
    networks:
      - player_network

  db_mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playerdb
    ports:
      - "3306:3306"
    volumes:
      - playerdb_data_mysql:/var/lib/mysql
    networks:
      - player_network

volumes:
  playerdb_data_mysql:
