networks:
  player_network:
    driver: bridge

services:
  playerapi:
    build: .
    image: playerapi-node
    ports:
      - "80:8080"  # El puerto del host y del contenedor.
    depends_on:
      db_mysql:
        condition: service_healthy
    environment:
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_HOST=db_mysql
      - MYSQL_DATABASE=playerdb
      - MYSQL_PORT=3306
    networks:
      - player_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db_mysql:
    image: mysql:8.0.35
    command: 
      - --performance_schema=OFF
      - --table_open_cache=128
      - --innodb_buffer_pool_size=256M
      - --max_connections=50
      - --sort_buffer_size=2M
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: playerdb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - playerdb_data_mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - player_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  playerdb_data_mysql: