name: Deno API CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for Player API
      run: |
        docker build -t playerapi-deno .

    - name: Run Player API in Docker container
      run: |
        docker run -d -p 8080:8080 --name playerapi playerapi-deno
      # Espera un par de segundos para asegurarse de que el contenedor esté en funcionamiento antes de las pruebas.
    - name: Wait for API to start
      run: sleep 10

    - name: Install Python Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install requests

    - name: Run API Tests
      run: |
        python3 ./PythonTestPlayerApi.py

    - name: Stop and Remove Docker Container
      if: always()
      run: |
        docker stop playerapi
        docker rm playerapi
