name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      working-directory: ./PlayerApi
      run: dotnet restore

    - name: Build
      working-directory: ./PlayerApi
      run: dotnet build --configuration Release

    - name: Publish
      working-directory: ./PlayerApi
      run: dotnet publish --configuration Release --output ./publish

    - name: Run tests
      working-directory: ./PlayerApi.Tests
      run: dotnet test --verbosity normal