name: Deno API CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Deno
      run: |
        curl -fsSL https://deno.land/install.sh | sh
        echo "Deno installed"

    - name: Add Deno to Path
      shell: bash
      run: |
        echo "${HOME}/.deno/bin" >> $GITHUB_PATH

    - name: Run API with Deno in Background
      run: |
        nohup deno run --allow-net index.ts &
      # Espera unos segundos para asegurarse de que la API está levantada antes de los tests.
    - name: Wait for API to Start
      run: sleep 10

    - name: Install Python Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install requests

    - name: Run API Tests
      run: |
        python3 ./PythonTestPlayerApi.py
